"""empty message

Revision ID: 02b0a11c7df1
Revises: e011075e34a7
Create Date: 2022-04-29 10:45:14.925407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b0a11c7df1'
down_revision = 'e011075e34a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_puzzles', sa.Column('score', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_puzzles', 'puzzle', ['score'], ['score'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_puzzles', type_='foreignkey')
    op.drop_column('user_puzzles', 'score')
    # ### end Alembic commands ###
