"""empty message

Revision ID: 0cd9ea10401d
Revises: 1350101600fd
Create Date: 2022-04-17 10:58:17.104843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd9ea10401d'
down_revision = '1350101600fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('dimension', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'dimension')
    # ### end Alembic commands ###
