"""add association object

Revision ID: 65a261890ad1
Revises: f6bdad33df95
Create Date: 2022-05-05 17:41:56.901605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a261890ad1'
down_revision = 'f6bdad33df95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'puzzles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('puzzles', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
